scrumbe_get_projects:
    pattern:  /projects
    defaults: { _controller: ScrumbeProjectBundle:Project:getProjects }
    requirements:
        _method: GET

scrumbe_get_project:
    pattern:  /projects/{projectId}
    defaults: { _controller: ScrumbeProjectBundle:Project:getProject }
    requirements:
        id: \d+
        _method: GET
