scrumbe_get_projects:
    pattern:  /projects
    defaults: { _controller: ScrumbeProjectBundle:Project:getProjects }
    requirements:
        _method: GET

scrumbe_get_project:
    pattern:  /projects/{projectId}
    defaults: { _controller: ScrumbeProjectBundle:Project:getProject }
    requirements:
        projectId: \d+
        _method: GET

scrumbe_post_project:
    pattern:  /projects/create
    defaults: { _controller: ScrumbeProjectBundle:Project:postProject }
    requirements:
        _method: POST

scrumbe_put_project:
    pattern:  /projects/{projectId}/update
    defaults: { _controller: ScrumbeProjectBundle:Project:putProject }
    requirements:
        projectId: \d+

scrumbe_delete_project:
    pattern:  /projects/{projectId}/delete
    defaults: { _controller: ScrumbeProjectBundle:Project:deleteProject }
    requirements:
        projectId: \d+
        _method: GET

scrumbe_get_uss:
    pattern: /projects/{projectId}/us
    defaults: {_controller: ScrumbeProjectBundle:UserStory:getUss}
    requirements:
        projectId: \d+
        _method: GET


scrumbe_get_us:
    pattern: /projects/{projectId}/us/{usId}
    defaults: {_controller: ScrumbeProjectBundle:UserStory:getUs}
    requirements:
        projectId: \d+
        usId: \d+
        _method: GET

scrumbe_post_us:
    pattern: /projects/{projectId}/us/create
    defaults: {_controller: ScrumbeProjectBundle:UserStory:postUs}
    requirements:
        projectId: \d+

scrumbe_put_us:
    pattern: /projects/{projectId}/us/{usId}/update
    defaults: {_controller: ScrumbeProjectBundle:UserStory:putUs}
    requirements:
        projectId: \d+
        usId: \d+

scrumbe_delete_us:
    pattern: /projects/{projectId}/us/{usId}/delete
    defaults: {_controller: ScrumbeProjectBundle:UserStory:deleteUs}
    requirements:
        projectId: \d+
        usId: \d+
        _method: GET