parameters:
    project_service.class:    Scrumbe\Bundle\ProjectBundle\Services\ProjectService
    userstory_service.class:  Scrumbe\Bundle\ProjectBundle\Services\UserstoryService
    task_service.class:       Scrumbe\Bundle\ProjectBundle\Services\TaskService
    form.type.project.class:  Scrumbe\Bundle\ProjectBundle\Form\Type\ProjectType

services:
    project_service:
        class: %project_service.class%
        arguments: [@form.factory,@service_container]

    userstory_service:
        class: %userstory_service.class%
        arguments: [@form.factory,@service_container]

    task_service:
        class: %task_service.class%
        arguments: [@form.factory,@service_container]

    form.type.project:
            class: %form.type.project.class%
            tags:
                - { name: form.type, alias: project }