login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

scrumbe_post_user:
    pattern:  /users/create
    defaults: { _controller: ScrumbeUserBundle:User:postUser }
    requirements:
        _method: POST

scrumbe_validate_user:
    pattern: /users/{userId}/confirm
    defaults: { _controller: ScrumbeUserBundle:User:validateUser }
    requirements:
        userId: \d+
        _method: GET
