services:
    user.user_service:
        class: Scrumbe\Bundle\UserBundle\Services\UserService
        arguments: [@translator, @scrumbe_mailer]
    user_provider:
        class: Scrumbe\Bundle\UserBundle\Security\User\UserProvider
        arguments: [@user.user_service]
    form.type.user:
            class: Scrumbe\Bundle\UserBundle\Form\Type\UserType
            tags:
                - { name: form.type, alias: user }