index:
    pattern: /
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:index }

about:
    pattern: /a-propos
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:about }

scrum:
    pattern: /scrum
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:scrum }

offres:
    pattern: /offres
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:offres }

contact:
    pattern: /contact
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:contact }

beta_signin:
    pattern: /beta
    defaults: { _controller: ScrumbeFrontOfficeBundle:Home:beta }
    requirements:
        _method: POST